import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";

const poppins= Poppins(
  {
    weight:['100','200','400','500','600','800']
  }
)

export const metadata = {
  title: {
    default:"Hero kids",
    template: "%s | Hero kids",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}  antialiased`}> 
        <header className="py-2 md:w-11/12 mx-auto">
          <Navbar></Navbar>
        </header> 
        <main className="py-2 md:w-11/12 mx-auto min-h-[calc(100vh-320px)]"> {children} </main>
        
        <footer className="py-2 md:w-11/12 mx-auto">
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
