export const dynamic = "force-dynamic";

import React from 'react';
import Products from "@/Components/Home/Products";
export const metadata = {
  title: "All products",
  description: "Generated by create next app",
};
const ProductPage = () => {
    return (
        <div>
            <h2 className="text-center mx-auto font-bold bg-amber-400 rounded-full py-2 px-6 my-10 text-xl sm:text-2xl md:text-3xl lg:text-4xl w-fi">
          Here is all our product
            </h2>
            <Products></Products>
        </div>
    );
};

export default ProductPage;